- clean: ['~']

- link:
    ~/.gitconfig: gitconfig
    ~/.tmux.conf: tmux/tmuxconf
    ~/.vim: vim/
    ~/.vimrc: vim/vimrc
    ~/.oh-my-zsh: zsh/oh-my-zsh
    ~/.zshrc: zsh/zshrc    

- shell:
  - [git submodule update --init --recursive, Installing submodules]

