- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vim/vimrc
    ~/.zsh: zsh/
    ~/.zshrc: zsh/zshrc

- shell:
  - git submodule update --init --recursive
