#!/usr/bin/env bash

set -e

CONFIG=".install.config.yaml"
DOTBOT_DIR="dotbot"
PL_FONTS="fonts"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

echo ""
echo "Installing Powerline fonts..."
cd "${PL_FONTS}"
sudo bash install.sh
