#!/usr/bin/env bash

set -e

CONFIG=".install.conf.yaml"
DOTBOT_DIR="$HOME/.dotfiles/dotbot"

DOTBOT_BIN="$HOME/.dotfiles/dotbot/bin"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo $CONFIG
echo $DOTBOT_DIR
echo $DOTBOT_BIN
echo $BASEDIR

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
